### ISSUE TITLE
[Flight-Booking] Implement Landing Page View

### ISSUE THREAD

**Issue by morinaltin** [altinim/job-application-system#4]
### Description: 
 As a user in the landing page view,
 want to have a tab view within the landing page with a a form for booking flights, reserving hotels and cars where the view of the form changes for each tab click without leaving the landing page.

### Tasks:
- [x] Create a tab view with three tabs, Flights, Hotels, and cars.
- [x] Place the view of the tab in the center of the landing page.
- [x] Create a form for the Flights tab with the inputs of the origin location, the estimated location, departure, the passenger count, and the search button.
